# Generated by Django 5.0.6 on 2024-07-05 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('l_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_contact_no', models.CharField(max_length=10)),
                ('emp_address', models.CharField(max_length=20)),
                ('emp_designation', models.CharField(max_length=20)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMS.department')),
            ],
        ),
        migrations.CreateModel(
            name='emp_os',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('os_salary', models.IntegerField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMS.emp')),
            ],
        ),
        migrations.CreateModel(
            name='emp_wfh',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wfh_salary', models.IntegerField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMS.emp')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_description', models.CharField(max_length=20)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMS.department')),
            ],
        ),
        migrations.CreateModel(
            name='takes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_date', models.DateField()),
                ('t_retdate', models.DateField()),
                ('l_available', models.IntegerField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMS.emp')),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMS.leave')),
            ],
        ),
    ]
