# Generated by Django 5.0.6 on 2024-07-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='dept_id',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='emp_os',
            old_name='emp_id',
            new_name='emp',
        ),
        migrations.RenameField(
            model_name='emp_wfh',
            old_name='emp_id',
            new_name='emp',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='dept_id',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='takes',
            old_name='emp_id',
            new_name='emp',
        ),
        migrations.RenameField(
            model_name='takes',
            old_name='l_id',
            new_name='l',
        ),
    ]
